// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Text.Json.Serialization;
using SiteOfRefuge.API;
using static SiteOfRefuge.API.Shared;

namespace SiteOfRefuge.API.Models
{
    /// <summary> The Availability. </summary>
    public partial class Availability
    {
        /// <summary> Initializes a new instance of Availability. </summary>
        public Availability()
        {
        }

        /// <summary> Initializes a new instance of Availability. </summary>
        /// <param name="id"> Unique identifier in UUID/GUID format. </param>
        /// <param name="date_Available"> Date when shelter will be available. </param>
        /// <param name="active"> Is this shelter currently available for matching with refugees?. </param>
        /// <param name="length_Of_Stay"> How long a refugee can stay. </param>
        internal Availability(Guid? id, DateTime? date_Available, bool? active, AvailabilityLengthOfStay? length_Of_Stay)
        {
            Id = id;
            Date_Available = date_Available;
            Active = active;
            Length_Of_Stay = length_Of_Stay;
        }

        /// <summary> Unique identifier in UUID/GUID format. </summary>
        public Guid? Id { get; set; }
        /// <summary> Date when shelter will be available. </summary>
        public DateTime? Date_Available { get; set; }
        /// <summary> Is this shelter currently available for matching with refugees?. </summary>
        public bool? Active { get; set; }
        /// <summary> How long a refugee can stay. </summary>
        public AvailabilityLengthOfStay? Length_Of_Stay { get; set; }
    }
}
