// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace SiteOfRefuge.API.Models
{
    /// <summary> Contact information of a person. </summary>
    public partial class Contact
    {
        public Contact() {}

        /// <summary> Initializes a new instance of Contact. </summary>
        /// <param name="firstname"> The person&apos;s first name. </param>
        /// <param name="lastname"> The person&apos;s last name. </param>
        /// <param name="methods"> The way(s) in which this person can be contacted. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="name"/> or <paramref name="methods"/> is null. </exception>
        public Contact(string firstname, string lastname, IList<ContactMode> methods)
        {
            if (firstname == null)
            {
                throw new ArgumentNullException(nameof(firstname));
            }
            if (lastname == null)
            {
                throw new ArgumentNullException(nameof(lastname));
            }
            if (methods == null)
            {
                throw new ArgumentNullException(nameof(methods));
            }

            FirstName = firstname;
            LastName = lastname;
            Methods = methods;
        }

        /// <summary> Initializes a new instance of Contact. </summary>
        /// <param name="id"> Unique identifier in UUID/GUID format. </param>
        /// <param name="firstname"> The person&apos;s first name. </param>
        /// <param name="lastname"> The person&apos;s last name. </param>
        /// <param name="methods"> The way(s) in which this person can be contacted. </param>
        internal Contact(Guid? id, string firstname, string lastname, IList<ContactMode> methods)
        {
            Id = id;
            FirstName = firstname;
            LastName = lastname;
            Methods = methods;
        }

        /// <summary> Unique identifier in UUID/GUID format. </summary>
        public Guid? Id { get; set; }
        /// <summary> The person&apos;s first name. </summary>
        public string FirstName { get; set; }
        /// <summary> The person&apos;s last name. </summary>
        public string LastName { get; set; }
        /// <summary> The way(s) in which this person can be contacted. </summary>
        public IList<ContactMode> Methods { get; set; }
    }
}
