// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace SiteOfRefuge.API.Models
{
    /// <summary> An invitation to connect. </summary>
    public partial class Invite
    {
        public Invite() {}
        
        /// <summary> Initializes a new instance of Invite. </summary>
        /// <param name="refugeeId"> Unique identifier in UUID/GUID format. </param>
        /// <param name="hostId"> Unique identifier in UUID/GUID format. </param>
        internal Invite(Guid refugeeId, Guid hostId)
        {
            RefugeeId = refugeeId;
            HostId = hostId;
        }

        /// <summary> Initializes a new instance of Invite. </summary>
        /// <param name="refugeeId"> Unique identifier in UUID/GUID format. </param>
        /// <param name="hostId"> Unique identifier in UUID/GUID format. </param>
        /// <param name="dateRequested"> Date when inivitation was sent. </param>
        /// <param name="dateAccepted"> Date when inivitation was accepted. </param>
        internal Invite(Guid refugeeId, Guid hostId, string message, DateTime dateSent, DateTime? refugeeRescinded,
        DateTime? hostRescinded, DateTime expirationDate, DateTime? acceptedDate, DateTime? dateToClose, 
        DateTime? completedDate, bool archived)
        {
            RefugeeId = refugeeId;
            HostId = hostId;
            this.Message = message;
            this.DateSent = dateSent;
            this.RefugeeRescinded = refugeeRescinded;
            this.HostRescinded = hostRescinded;
            this.ExpirationDate = expirationDate;
            this.AcceptedDate = acceptedDate;
            this.DateToClose = dateToClose;
            this.CompletedDate = completedDate;
            this.Archived = archived;
        }

        public Guid RefugeeId { get; set; }
        public Guid HostId { get; set; }
        public string Message { get; set; }
        public DateTime DateSent { get; set; }
        public DateTime? RefugeeRescinded { get; set; }
        public DateTime? HostRescinded { get; set; }
        public DateTime ExpirationDate { get; set; }
        public DateTime? AcceptedDate { get; set; }
        public DateTime? DateToClose { get; set; }
        public DateTime? CompletedDate { get; set; }
        public bool Archived { get; set; }
    }
}
